 # Trajectory
 autosize: true
 dt_ref: 0.5
 dt_hysteresis: 0.1
 min_samples: 3
 max_samples: 500

 # Robot
 max_vel_x: 0.35
 max_vel_x_backwards: 0.1
 max_vel_theta: 0.1
 acc_lim_x: 0.5
 acc_lim_theta: 0.1
 min_turning_radius: 1.6

 footprint_model:
  type: "polygon"
  vertices: [[0.65, 0.38], [-0.75, 0.38], [-0.75, -0.38], [0.65, -0.38]]

 # Obstacles
 min_obstacle_dist: 1 # This value must also include our robot radius, since footprint_model is set to "point".

 # Optimization
    
 penalty_epsilon: 0.1
 weight_max_vel_x: 200
 weight_max_vel_theta: 10
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 0

 obstacle_noise: 0.1
 time_noise: 0.1
 velocity_noise: 0.01
 kinematic_noise: 0.001



 
